### ISSUE TITLE
Role->Role - échéance

### ISSUE THREAD

**Issue by ymlesaux** [dnum-mi/canel-specs#15]
**Reprise Issues**
[METAZEL] rajouter un moyen de savoir si le rôle est toujours valide. Maitriser la sécurité autour du rôle (le désenrôlement se fait mal dans notre structure, il faut donc gérer un rafraichissement régulier de son statut)
[YMLESAUX]  La table Acteur actuelle contient un champ "actif", qui est plutôt à porter par le rôle.
Une stratégie possible est de mettre une date d'échéance par principe, ce qui amènera à rafraichir périodiquement les données.
A discuter

**Comment by ymlesaux** [comment]
Proposition évolution Application.md:

ajout d'un attribut de l'objet Rôle:
- Date échéance [obligatoire] - date à laquelle le rôle est échu, ou bien doit être mis à jour
    - Exigence : la date d'échéance, lors de sa définition ou sa mise à jour, ne peut dépasser 2 ans par rapport à la date courante
    - Exigence: 10 jours calendaires avant échéance, un message est envoyé aux souscripteurs et chef de projet pour les alerter
 
ajout d'une exigence pour l'objet Acteur:
    - Exigence: Si un acteur n'a plus de rôle valide depuis 1 an,  son nom et son adresse mail sont anonymisées

**Comment by Metazel** [comment]
# objet Rôle:
- Date échéance [obligatoire] : la valeur de la date d'échéance doit être paramétrable. La date du rôle devrait être plus petite ou égale à la date d'inactivation de l'acteur, non?
- Transmission du message d'alerte au souscripteur 10 jours avant échéance =>Ok (et auprès de l'acteur concerné?)

# objet Acteur : 
- faire une bascule en plusieurs étapes  : une inactivation de ces accès aux données (ses rôles passent a échu) au bout de X mois, un message d'alerte auprès de l'acteur concerné au moment de la désactivation des rôles, puis au bout de X mois supplemntaires, une anonymisation de l'acteur?

**Comment by ymlesaux** [comment]
OK pour l'essentiel, mais il n'y a pas de date d'échéance directement pour un acteur: cette date d'échéance est égale au maximum des dates d'échéance des rôles associés; donc pas de stockage explicite, juste cette règle de gestion.

Par contre, en relisant, il y a un cas qui passe entre les mailles du filet (pour les acteurs): le cas d'un acteur créé sans aucun rôle. J'ajoute donc une Exigence dans ce sens.

**Adaptation de la proposition initiale**
ajout d'un attribut de l'objet Rôle:

    Date échéance [obligatoire] - date à laquelle le rôle est échu, ou bien doit être mis à jour
        Exigence : la date d'échéance, lors de sa définition ou sa mise à jour, ne peut dépasser 2 ans par rapport à la date courante
        Exigence: la durée maximum de la date d'échéance doit être paramétrable
        Exigence: 10 jours calendaires avant échéance, un message est envoyé à l'acteur concerné, aux souscripteurs et au chef de projet pour les alerter

ajout d'une exigence pour l'objet Acteur:
- Exigence: Si un acteur n'a plus de rôle valide depuis 1 an, son nom et son adresse mail sont anonymisées
- Exigence: La durée mentionnée dans l'exigence précédente (1 an) doit être paramétrable (décompte en mois)
- Exigence: Si un acteur n'a aucun rôle associé, le début de la période avant anonymisation est la date de dernière modification de cet acteur.

**Comment by ymlesaux** [comment]
Ajouter une date de référence sur l'acteur qui sera calculée selon les règles suivantes:
A la création de l'acteur, ou sa mise à jour, date de référence = date modif
A la modification d'un rôle, date de référence = date d'échéance max des rôles
