### ISSUE TITLE
Acteur->RIO

### ISSUE THREAD

**Issue by ymlesaux** [dnum-mi/canel-specs#16]
**Version Initiale**
_RIO [facultatif] - A REVOIR: donnée spécifique MI; pour quel usage ?_

**Reprise Issues**
[METAZEL] RIO : propre a notre organisation. Pareil que pour Application, je propose de la lier a un objet "Identifiants externes". Le RIO est l'id unique pour un agent du MI.
[YMLESAUX] L'externaliser signifie qu'un acteur pourrait avoir plusieurs identifiants, donc pourquoi pas mais à challenger avec charge de réalisation et gestion.
Mais reste toujours la question du pourquoi stocker cette information ? Pour un acteur, nous disposons de son adresse de messagerie, qui est une clé de partage simple avec la console DSO.
Si l'identification via Passage2 nous fournit l'adresse de messagerie (à confirmer), en quoi avons-nous besoin du RIO ?
[MOGADOR26] le numéro de RIO n'est pas utile, mais il doit rester un identifiant interne

**Comment by ymlesaux** [comment]
Supprimer le RIO des attributs Acteur
Créer une table de référence des types d'identifiant Acteur
Créer une table des identifiants Acteur

**Comment by Metazel** [comment]
Proposition de partir sur un principe analogue aux identifiants d'une application et de nommer la table de references des types d'identifiant et la table association des identifiants d'un acteur de la meme manière et avec les mêmes attributs.

**Comment by Metazel** [comment]
Cf Issue https://github.com/dnum-mi/canel2/pull/27 dans Canel2
