### ISSUE TITLE
[Acteurs] : données

### ISSUE THREAD

**Issue by mogador26** [dnum-mi/canel-specs#2]
Dans les attributs de l'objet Acteurs on peut considérer que :

- le numéro de RIO n'est pas utile;
- le type d'acteur peut être confondu avec le rôle lié à une application;
- l'habilitation ne doit pas être référencée

Il doit rester :
- identifiant interne
- email
- nom
- entité de rattachement (ex: direction/sous-direction)

**Comment by ymlesaux** [comment]
Le RIO est discuté dans l'issue #16
Le Type Acteur est discuté dans l'issue #18
Retirer l'attribut Habilitation de l'acteur
Entité de rattachement: préciser dans la spécification qu'il s'agit de l'employeur

**Comment by Metazel** [comment]
Cf Issue https://github.com/dnum-mi/canel2/pull/27 dans Canel2
