### ISSUE TITLE
Gestion des droits des utilisateurs _ accès a la fonction "Delete" d'un objet

### ISSUE THREAD

**Issue by Metazel** [dnum-mi/canel-specs#23]
Dans le document,
On décrit les rôles et les droits en CRU sur les objets.
Aucun n'a le droit à la suppression de données. 
Que fait-on dans le cas d'une saisie en erreur qui polluerait le référentiel?
Manque-t-il un rôle ou fournit on le droit à l'administrateur fonctionnel (celui-ci ne devrait il pas avoir les  droits de type RUD pour modifier ou supprimer une information?)

**Comment by ymlesaux** [comment]
Fichier GestionDroits.md
Tableau de droits revu selon contribution Mattermost de Maxime.
Les logiques de purge doivent faire l'objet d'une spécification particulière, ou d'une évolution des spécifications existantes pour préciser les conditions et périmètres de purge.
Hors de ce champ, je ne pense pas qu'il soit pertinent de permettre une suppression physique des objets métiers.
Par contre, nous devons vérifier que chaque objet dispose d'une capacité d’inactivation:
- Application: attribut "statut" permet d'identifier les applications décommissionnées
- Rôle : notion d'échéance décrite dans la spécification #15 
- Acteur: pas d'inactivation explicite, mais sous contrainte des rôles associés. Le mécanisme d'anonymisation doit être décrit dans l'issue #15.
- Conformité : date d'échéance portée; historique intéressant
- Instance : attribut "statut permet d'identifier les instances décommissionnées; par contre, rien de spécifié sur la relation entre les statuts des instances et le statut de l'application.
- Environnement: pas d'information définissant le statut de l'environnement; évolution à prévoir
- Pile technique: est lié à l'objet Application
- Technologie: ne contient pas d'indicateur pour désactiver une technologie; à relier au CCT si celui ci interdit ou autorise des technologies.

**Comment by mogador26** [comment]
- je ne pense pas qu'il soit pertinent de permettre une suppression physique des objets métiers :+1:
