### ISSUE TITLE
Application -> type d'architecture

### ISSUE THREAD

**Issue by Metazel** [dnum-mi/canel-specs#28]
Je pense qu'il y a un intérêt à identifier le type d'architecture mise en œuvre. Notamment pour connaitre la complexité, le niveau de couplage d'une application, si elle se rapproche d'un cadre de développement (par exemple Cloud Native) impliquant des bonnes pratiques et une architecture de type : microservices, event driven architecture. 

Je vois la liste suivante : 
- architecture monolithique
- architecture en couches
- architecture orienté services
- architecture en microservices
- architecture event driven

**Comment by mogador26** [comment]
nous n'aurons pas ce niveau de détail et la subtilité de certaine définition d'architecture entre orienté services et microservices sera difficilement appréhandable.

**Comment by mogador26** [comment]
issue #10
