### ISSUE TITLE
Application->Statut

### ISSUE THREAD

**Issue by Metazel** [dnum-mi/canel-specs#33]
Le champ **Statut** d'une Application doit proposer les valeurs suivantes : 
- En Construction: l'application est en cours de d'édition (développement, intégration)
- En Production: l'application est déployée sur sa plateforme de production; le service peut être ouvert ou non
- En cours de retrait de service: l'application est inscrite sur une trajectoire de retrait, mais est toujours opérationnelle
- Retirée du service: l'accès opérationnel à l'application n'est plus ouvert, mais les instances sont maintenues (contraintes techniques ou réglementaires)
- Décommissionnée: l'application a été physiquement retirée des plateformes de production

**Comment by ymlesaux** [comment]
Issue #23 de canel2
