### ISSUE TITLE
[Applications] Unicité d'une application

### ISSUE THREAD

**Issue by mogador26** [dnum-mi/canel-specs#42]
L'unicité d'une application est contrôlée au sein du système applicatif CANEL. Une application est dite unique dés lors qu'elle n'est référencée qu'une seule fois au sein d'un organisme.

Exemple :
|Nom|organismes|actions|etat|
|-----|-----------|-----|-----|
|CANEL| MI|enregistré|OK|
|CANEL|MJ|enregistré|OK|
|*CANEL*|MI|tentative d'enregistrement|KO|

Suite au contrôle effectué l'API renverra, pour le dernier cas du tableau précédent, un code HTTP 409 indiquant un conflit (ou doublon).

**Comment by Metazel** [comment]
Ok pour moi.
Mettre cette contrainte d'inégrité comme contrôle en préalableà toute action d'intégration d'une application. 
Création par API, création au travers de l'IHM, restauration de base ....

**Comment by ymlesaux** [comment]
Lors d'une restauration de base, les contrôles applicatifs se sont pas applicables.
La création par l'IHM faisant appel à l'API, le contrôle par l'API est suffisant.
