### ISSUE TITLE
[FluxApplication]

### ISSUE THREAD

**Issue by Metazel** [dnum-mi/canel-specs#45]
Champ "intermédiaire" : peut-on l'appeler "application de transport" ou "intergiciel" (ma préférence) ?

Est-ce qu'un champ "nature de l'échange" serait utile :"synchrone, asynchrone," pouvant être complété par "push (comme pour les systèmes d'alerting/notification), pull (invocation d'api)"?

Est-ce qu'un champ "format" du flux serait utile : "json, xml, txt, csv" ?

Est-ce qu'un champ "mecanime d'authentification" entre systèmes serait utile  (je suis pas specialiste @hassan)?

Question : un flux est-il forcément entre deux systèmes applicatifs? Comment gérer la méconnaissance qu'on a d'un flux entre une application maitrisée chez nous et une application X (dont on ne connait pas le nom) gérée par une entité organisationnelle externe (ex. IGN, ou une entité affiliée au MIOM mais sur lequel on ne connait pas les applications ex. ANTS ou ANTS)?

Question : la partie donnée(s) véhiculée(s) par un flux. Gère-t-on l'information dans CANEL2 ou collecte-t-on nous l'information à partir du catalogue de données?

**Comment by ymlesaux** [comment]
_Champ "intermédiaire" : peut-on l'appeler "application de transport" ou "intergiciel" (ma préférence) ?_
Ce terme est repris du modèle de DAG. Peu importe le terme du moment qu'il fait sens pour tous les utilisateurs, et qu'il est identique dans tous les media.

_Est-ce qu'un champ "nature de l'échange" serait utile :"synchrone, asynchrone," pouvant être complété par "push (comme pour les systèmes d'alerting/notification), pull (invocation d'api)"?_
La notion d'asynchronisme requiert un composant intermédiaire. Soit il s'agit d'un composant managé, et il est alors précisé dans le champ "intermédiaire", soit il s'agit d'un composant applicatif, et il devrait apparaitre explicitement.
Donc, pas convaincu.
Pour la question sur les "push/pull": cela permettrait de préciser le sens de circulation des données, dans la mesure où le sens de la connexion (applications source et cible) est technique (qui initialise la connexion) - A discuter

_Est-ce qu'un champ "format" du flux serait utile : "json, xml, txt, csv" ?_
Dans l'absolu, oui, mais bof: cela fait sens dans le cas d'une interface pour préciser le format attendu, mais dans le cas d'un flux, je suis moins convaincu.

_Est-ce qu'un champ "mecanime d'authentification" entre systèmes serait utile (je suis pas specialiste @hassan)?_
Un peu comme au-dessus, cette information est intéressant pour une interface, et moins pour un flux.

_Question : un flux est-il forcément entre deux systèmes applicatifs? Comment gérer la méconnaissance qu'on a d'un flux entre une application maitrisée chez nous et une application X (dont on ne connait pas le nom) gérée par une entité organisationnelle externe_
Je n'ai pas compris la différence entre ANTS et ANTS :)
Plus sérieusement, la remarque est pertinente. As tu une proposition ?

_Question : la partie donnée(s) véhiculée(s) par un flux. Gère-t-on l'information dans CANEL2 ou collecte-t-on nous l'information à partir du catalogue de données?_
D'après ce que j'ai cru écrire, le champ Identifiant de la donnée permet de collecter une donnée issue d'un référentiel de données. Mais en attendant, on pourrait y mettre un nom. Je ne crois pas avoir mis de contrainte sur ce sujet.
