### ISSUE TITLE
Application->Statut

### ISSUE THREAD

**Issue by ymlesaux** [dnum-mi/canel-specs#5]
**Version initiale**
_Statut de l'application [obligatoire] - Enum [En construction, En production, En cours de retrait, Mise en extinction, Décommissionnée, Identifiée dans la trajectoire] - A REVOIR: la liste pose question, et doit être alignée avec les statuts des instances_

**Reprise Issues**
[METAZEL] Champs "statut" : on avait revu la liste, mais elle ne semble pas reprise. Ce qui avait été demandé était de ne garder que les valeurs suivantes "En construction", "En production", "En cours de retrait", "Décommissionnée". Et je ne le mettrais pas en obligatoire (car les sources n'auront pas forcément ce type d'information)
PS : le cycle de vie d'une application passe généralement dans les stades suivants... plus ou moins à vision opérationnelle : application nouvelle (ajout), déployée, services ouverts, en maintenance, en retrait (service arrêté temporairement ou définitivement), supprimée (décommissionnée ou remplacée)
[YMLESAUX]  Les données d'énumération utilisées dans toutes ces spécifications sont issues du code "Clean-Refacto". Quelle source pour la liste corrigée ? En tout cas, il faut que les valeurs fassent sens, mais restent maintenables. Donc, pour chaque valeur proposée, il faudra associer une définition.

**Comment by Metazel** [comment]
Issue retenue et reprise dans la spec

**Comment by ymlesaux** [comment]
Valeurs de la table de référence retenues:
- En construction: l'application est en développement ou intégration.
- En production: l'application est sur sa plateforme de production; le service peut être ouvert ou non
- En cours de retrait de service
- Retiré du service
- Décommissionné

**Comment by Metazel** [comment]
Cf. Issue https://github.com/dnum-mi/canel-specs/issues/23 dans Canel2.
