### ISSUE TITLE
Application->Ministère responsable

### ISSUE THREAD

**Issue by ymlesaux** [dnum-mi/canel-specs#6]
**Version initiale**
_Ministère responsable [obligatoire]_

**Reprise Issues**
[METAZEL] Remarque: la solution se veut opensource donc agnostique du contexte d'entreprise. Il faut à mon sens supprimer les particularisme de notre structure.
Propositions :
Ministère responsable => Organisation responsable

[YMLESAUX] D'accord sur le renommage du champ, mais impact à gérer sur la version en cours.

**Comment by mogador26** [comment]
|Libellé long|Libellé court|
|------|-----|
|Ministère de l'intérieur et des outre-mer|MI|
|Ministère de la justice|MJ|
|Ministère des armées|MA|
|Ministère de l'Europe et des affaires étrangères|MEAE|
|Ministère de l'éducation nationale|MEN|
|Ministère de la transition écologique|MTE|
|Ministère de l'économie et des finances|MEF|

**Comment by mogador26** [comment]
remplacer  Ministère responsable par Organisation responsable

**Comment by ymlesaux** [comment]
Ajouter encore:

| **Libellé long** | **Libellé court** |
|---------------------------|----------------|
| Ministère de la Cuture | MC |
| Ministère du Travail | MT |
| Ministère de l'Agriculture | MAG |
| Ministère de la Santé et de la Prévention | MS |

**Comment by Metazel** [comment]
Issue a mettre a jour dans la spec. 
Nom du champ "Organisme responsable" faisant référence aux valeurs de la table suivante :
|  Libellé long | Libellé court|
|---|---|
| Ministère de l'intérieur et des outre-mer | MI |
| Ministère de la justice | MJ |
| Ministère des armées | MA |
| Ministère de l'Europe et des affaires étrangères | MEAE |
| Ministère de l'éducation nationale | MEN |
| Ministère de la transition écologique | MTE |
| Ministère de l'économie et des finances | MEF |
| Ministère de la Cuture | MC |
| Ministère du Travail | MT |
| Ministère de l'Agriculture | MAG |
| Ministère de la Santé et de la Prévention | MS |
| Ministère de l'Enseignement supérieur et de la Recherche | MESR |
| Ministère des Solidarités, de l'Autonomie et des Personnes handicapées | MSAPH |
| Ministère de la Transformation et de la Fonction publiques | MTFP |
| Ministère des Sports | MSJOP |
| Premier ministre | PM |

**Comment by Metazel** [comment]
Cf. Issue https://github.com/dnum-mi/canel-specs/issues/24 dans Canel2.
