### ISSUE TITLE
Application->Identifiants externes

### ISSUE THREAD

**Issue by ymlesaux** [dnum-mi/canel-specs#7]
**Version Initiale**
_lien vers des identifiants [facultatif] - lien vers une liste d'identifiants issus d'autre systèmes
    - CANEL1
    - BAI2
    - GSP2
    - PAI_

**Reprise Issues**
[METAZEL] Identifiants externes : les gérer dans une table lié a l'objet (source / id / Label / [valeur locale, si transformation])
[YMLESAUX] Si l'on parle de la donnée "lien vers les identifiants", c'est bien ce qui est proposé, mais qui n'est pas implémenté aujourd'hui.
Sinon, merci de préciser.

**Comment by ymlesaux** [comment]
Ajouter une table de référence des types d'identifiants applicatifs
Ajouter une table des identifiants applicatifs reliant les applications à un type d'identifiant

**Comment by Metazel** [comment]
Cf. Issue https://github.com/dnum-mi/canel-specs/issues/25 dans Canel2
